service: hello-world

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: serverless.handler
    events:
      - http:
          path: /
          method: get
